"""Knowledge-base sources and chunks.

For v0.3 we keep embeddings as JSON-serialized float arrays + Python-side
cosine similarity for retrieval — the wiki is small (~30 chunks at launch) so
pgvector + HNSW is overkill. Swaps to pgvector in v0.5 when the wiki crosses
~1,000 chunks (autogenerated `whorl kb ingest --source ksu-mf743` etc.).

The schema mirrors the v0.3 plan's `kb_sources` + `kb_chunks` exactly, so
nothing prevents the swap later.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional
from uuid import UUID

from sqlalchemy import JSON, ForeignKey, Integer, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from whorl.db import Base
from whorl.models._common import new_uuid, now_utc


class KBSource(Base):
    """Where a wiki page or raw chunk came from (one row per ingest unit)."""

    __tablename__ = "kb_sources"

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=new_uuid)
    slug: Mapped[str] = mapped_column(String(120), unique=True, index=True)
    title: Mapped[str] = mapped_column(String(255))
    publisher: Mapped[Optional[str]] = mapped_column(String(120))
    url: Mapped[Optional[str]] = mapped_column(String(500))
    license: Mapped[Optional[str]] = mapped_column(String(80))
    kind: Mapped[str] = mapped_column(String(20))   # 'wiki' | 'raw_pdf' | 'raw_html' | 'json_api'
    last_fetched: Mapped[datetime] = mapped_column(default=now_utc)


class KBChunk(Base):
    """One retrieval-sized text fragment with an embedding and entity tags."""

    __tablename__ = "kb_chunks"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    source_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("kb_sources.id"), index=True)
    ordinal: Mapped[int] = mapped_column(Integer)
    text: Mapped[str] = mapped_column(Text)

    # Embedding stored as JSON array of floats. Cosine sim runs in Python.
    embedding: Mapped[list[float]] = mapped_column(JSON, default=list)

    chunk_type: Mapped[str] = mapped_column(String(8))   # 'wiki' | 'raw'
    entity_kind: Mapped[Optional[str]] = mapped_column(String(20))  # 'pest' | 'crop' | 'product' | 'moa' | 'alt_control' | 'region'
    entity_slug: Mapped[Optional[str]] = mapped_column(String(120), index=True)

    # Coarse tags for pre-filtering before cosine ranking.
    crops: Mapped[list[str]] = mapped_column(JSON, default=list)
    pests: Mapped[list[str]] = mapped_column(JSON, default=list)
    regions: Mapped[list[str]] = mapped_column(JSON, default=list)
    moa_groups: Mapped[list[str]] = mapped_column(JSON, default=list)

    citation: Mapped[str] = mapped_column(Text)            # display string like "KSU MF743, p.12"
    created_at: Mapped[datetime] = mapped_column(default=now_utc)
